In [12]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [13]:
#from pathlib import Path

#path importation
DATA_PATH = r"C:/Users/HP FOLIO\Downloads\btc-historical-data.csv"

print("The path has been loaded and ready to be read into data-frame.....")

The path has been loaded and ready to be read into data-frame.....

In [14]:
print("The data cleaning has started...")

#1. Read the data into data frame
df = pd.read_csv(
    DATA_PATH,
    na_values=["$", "?", "NA", "N/A", "", "NaN", "nan"],
    keep_default_na=True
)

print("The BTC historical data csv file has been read into data-frame and ready for exploration...")

df.info()

The data cleaning has started...
The BTC historical data csv file has been read into data-frame and ready for exploration...
<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        32 non-null     str
 1   Open        32 non-null     str
 2   High        32 non-null     str
 3   Low         32 non-null     str
 4   Avg         32 non-null     str
 5   Close       32 non-null     str
 6   Chg         32 non-null     float64
 7   Volume      32 non-null     str
 8   Vol Chg     31 non-null     float64
 9   Market Cap  32 non-null     str
 10  MCap Chg    31 non-null     float64
dtypes: float64(3), str(8)
memory usage: 2.9 KB

In [15]:
#2. Replace NAN with UNKNOWN

#Note: Since "Vol Chg" and "MCap Chg" are the only columns where there is missing values
#Note: we will iterate through the missing columns("Vol Chg" and "MCap Chg") with missing values instead of iterating through the whole columns and fill it will UNKNOWN

missing_columns = ["Vol Chg", "MCap Chg"]

df.head(50)

for col in missing_columns:
    if col in df.columns:
        df[col] = df[col].fillna("UNKNOWN")
    else:
        print(f"The column {col} is is not present in the data frame columns")

print("The missing values have been replaced by the string UNKNOWN")

The missing values have been replaced by the string UNKNOWN

In [16]:
#3. Dropping of Date Columns since we don't need for the model training
df = df.drop("Date", axis=1)

print("The date column has been dropped from the date-frame")

The date column has been dropped from the date-frame

In [17]:
#4. We want to remove the $ from all the columns where the symbol is used

print("Defining columns with $ symbol.....")

dollar_columns = ["Open", "High", "Low", "Avg", "Close", "Volume", "Market Cap"]

for col in dollar_columns:
    if col in df.columns:
        #df[col] = df[col].str.replace("$", "", regex=False).str.replace(",", "", regex=False).astype(float)
        df[col] = df[col].str.replace({"$": "", ",": ""})
    else:
        print(f"The column {col} cannot be found")

print("$ and , has been removed")

df.head(50)

Defining columns with $ symbol.....
$ and , has been removed

,Open,High,Low,Avg,Close,Chg,Volume,Vol Chg,Market Cap,MCap Chg
0,74498,75884,73963,74618,74130,-0.49300,29647598972,0.774,1483778854536,-0.556
1,70739,74807,70625,72679,74546,5.38000,29419881869,36.89,1492078794361,5.4
2,73062,73123,70618,71883,70728,-3.20000,21492305497,4.87,1415612202097,-3.19
3,72940,73719,72637,73088,73057,0.16000,20493703071,-15.42,1462191867005,0.127
4,71780,73358,71463,72391,72965,1.65000,24230353778,-1.1,1460334172649,1.64
5,71068,72871,70542,71568,71791,1.02000,24499067997,102.69,1436805528637,0.951
6,71936,72721,70880,71663,71116,-1.14000,12086955344,-11.48,1423263331230,-1.14
7,68831,72400,67798,70241,71935,4.51000,13654525047,27.82,1439625543278,4.49
8,69293,70225,68532,69224,68848,-0.64200,10682266995,76.26,1377814297508,-0.199
9,67291,69022,66633,67983,68987,2.52000,6060568753,48.08,1380563772241,2.51
10,66914,67472,66800,67121,67298,0.57300,4092702286,-30.61,1346721470647,0.542
11,66943,67235,66340,66863,66936,-0.00945,5898220274,-43.25,1339467704589,0.0818
12,68086,68595,65790,67339,66883,-1.77000,10393354233,2.76,1338373364914,-1.81
13,68121,69189,67572,68250,68119,-0.00341,10113716781,-19.5,1363069244631,-0.141
14,66703,68312,66025,67314,68217,2.27000,12564184691,15.72,1364993568906,2.28
15,65896,67979,65826,66600,66698,1.22000,10857285457,74.38,1334586636723,1.08
16,66341,66994,65237,66140,65987,-0.53500,6226367309,7.89,1320320264687,-0.515
17,66327,67181,65953,66448,66330,0.00529,5771186600,-53.36,1327160993217,0.0355
18,68761,69073,65593,67437,66320,-3.55000,12372850954,15.39,1326690254523,-3.58
19,71307,71372,68240,69926,68786,-3.54000,10722651995,11.93,1375931262523,-3.56
20,70526,71912,70416,71044,71322,1.13000,9579426428,-14.2,1426660899625,1.09
21,70778,71285,68984,70400,70554,-0.31700,11164883270,-25.24,1411294062053,-0.312
22,67847,71604,67600,69457,70775,4.32000,14934086989,72.19,1415714969126,4.23
23,69263,69456,67570,68549,67906,-1.96000,8672859483,68.4,1358322420155,-2.14
24,70535,70949,69391,70067,69391,-1.62000,5150024129,-51.75,1388039857494,-1.62
25,69922,71231,69560,70312,70534,0.87600,10673115234,-13.66,1410901432550,0.928
26,71267,71510,68996,70414,69886,-1.94000,12361046934,-0.711,1397928216778,-1.99
27,73950,74565,70710,72632,71304,-3.58000,12449539568,-11.96,1426297410720,-3.61
28,74829,75876,73632,74578,73977,-1.14000,14140467823,-11.14,1479755926845,-1.13
29,72845,74850,72413,73733,74823,2.72000,15913429651,98.31,1496678780947,2.95
30,71208,73008,70914,71953,72681,2.07000,8024544662,30.86,1453810885371,2.12
31,70951,71284,70439,70962,71172,0.31100,6131926323,UNKNOWN,1423597839829,UNKNOWN

In [22]:
#5. Removal of whitespaces.

for col in df.columns:
    df[col] = df[col].astype(str).str.strip()

print("The whitespaces have been stripped, Feel free to add naked😂")

#6. Removal of last line from the data-frame because it contains incomplete data and we don't want it to corrupt our model during training
df = df.iloc[0:31]


df.info()

df.head(50)

The whitespaces have been stripped, Feel free to add naked😂
<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Open        31 non-null     str
 1   High        31 non-null     str
 2   Low         31 non-null     str
 3   Avg         31 non-null     str
 4   Close       31 non-null     str
 5   Chg         31 non-null     str
 6   Volume      31 non-null     str
 7   Vol Chg     31 non-null     str
 8   Market Cap  31 non-null     str
 9   MCap Chg    31 non-null     str
dtypes: str(10)
memory usage: 2.6 KB

,Open,High,Low,Avg,Close,Chg,Volume,Vol Chg,Market Cap,MCap Chg
0,74498.0,75884.0,73963.0,74618.0,74130.0,-0.493,29647598972.0,0.774,1483778854536.0,-0.556
1,70739.0,74807.0,70625.0,72679.0,74546.0,5.38,29419881869.0,36.89,1492078794361.0,5.4
2,73062.0,73123.0,70618.0,71883.0,70728.0,-3.2,21492305497.0,4.87,1415612202097.0,-3.19
3,72940.0,73719.0,72637.0,73088.0,73057.0,0.16,20493703071.0,-15.42,1462191867005.0,0.127
4,71780.0,73358.0,71463.0,72391.0,72965.0,1.65,24230353778.0,-1.1,1460334172649.0,1.64
5,71068.0,72871.0,70542.0,71568.0,71791.0,1.02,24499067997.0,102.69,1436805528637.0,0.951
6,71936.0,72721.0,70880.0,71663.0,71116.0,-1.14,12086955344.0,-11.48,1423263331230.0,-1.14
7,68831.0,72400.0,67798.0,70241.0,71935.0,4.51,13654525047.0,27.82,1439625543278.0,4.49
8,69293.0,70225.0,68532.0,69224.0,68848.0,-0.642,10682266995.0,76.26,1377814297508.0,-0.199
9,67291.0,69022.0,66633.0,67983.0,68987.0,2.52,6060568753.0,48.08,1380563772241.0,2.51
10,66914.0,67472.0,66800.0,67121.0,67298.0,0.573,4092702286.0,-30.61,1346721470647.0,0.542
11,66943.0,67235.0,66340.0,66863.0,66936.0,-0.00945,5898220274.0,-43.25,1339467704589.0,0.0818
12,68086.0,68595.0,65790.0,67339.0,66883.0,-1.77,10393354233.0,2.76,1338373364914.0,-1.81
13,68121.0,69189.0,67572.0,68250.0,68119.0,-0.00341,10113716781.0,-19.5,1363069244631.0,-0.141
14,66703.0,68312.0,66025.0,67314.0,68217.0,2.27,12564184691.0,15.72,1364993568906.0,2.28
15,65896.0,67979.0,65826.0,66600.0,66698.0,1.22,10857285457.0,74.38,1334586636723.0,1.08
16,66341.0,66994.0,65237.0,66140.0,65987.0,-0.535,6226367309.0,7.89,1320320264687.0,-0.515
17,66327.0,67181.0,65953.0,66448.0,66330.0,0.00529,5771186600.0,-53.36,1327160993217.0,0.0355
18,68761.0,69073.0,65593.0,67437.0,66320.0,-3.55,12372850954.0,15.39,1326690254523.0,-3.58
19,71307.0,71372.0,68240.0,69926.0,68786.0,-3.54,10722651995.0,11.93,1375931262523.0,-3.56
20,70526.0,71912.0,70416.0,71044.0,71322.0,1.13,9579426428.0,-14.2,1426660899625.0,1.09
21,70778.0,71285.0,68984.0,70400.0,70554.0,-0.317,11164883270.0,-25.24,1411294062053.0,-0.312
22,67847.0,71604.0,67600.0,69457.0,70775.0,4.32,14934086989.0,72.19,1415714969126.0,4.23
23,69263.0,69456.0,67570.0,68549.0,67906.0,-1.96,8672859483.0,68.4,1358322420155.0,-2.14
24,70535.0,70949.0,69391.0,70067.0,69391.0,-1.62,5150024129.0,-51.75,1388039857494.0,-1.62
25,69922.0,71231.0,69560.0,70312.0,70534.0,0.876,10673115234.0,-13.66,1410901432550.0,0.928
26,71267.0,71510.0,68996.0,70414.0,69886.0,-1.94,12361046934.0,-0.711,1397928216778.0,-1.99
27,73950.0,74565.0,70710.0,72632.0,71304.0,-3.58,12449539568.0,-11.96,1426297410720.0,-3.61
28,74829.0,75876.0,73632.0,74578.0,73977.0,-1.14,14140467823.0,-11.14,1479755926845.0,-1.13
29,72845.0,74850.0,72413.0,73733.0,74823.0,2.72,15913429651.0,98.31,1496678780947.0,2.95
30,71208.0,73008.0,70914.0,71953.0,72681.0,2.07,8024544662.0,30.86,1453810885371.0,2.12

In [19]:
#6. Initialization of model training

print("Intialization of model training....")

#First let's convert the type of each column back to float because they have been converted to str during stripping

for col in df.columns:
    df[col] = df[col].astype(float)

#Note: Row 2 be our "y" and make row 3 - 30 "X".  We are doing this because
#1. We want to train our data with a large data
#2. After the model has been trained we want to test the model with row 0. i.e. we will input row 1 into the model to predict row 0 and cross the predicted values with actual values of row 1

our_sample = df.iloc[0:3]

y = df.iloc[3:17]
#y = y.apply(pd.to_numeric, errors='coerce')
print(f"Our y is {y}")
print(f"its length is {len(y)}")

#X = X.apply(pd.to_numeric, errors='coerce')

X = df.iloc[17:31]
#X = X.apply(pd.to_numeric, errors='coerce')
print(f"Our X is {X}")
print(f"its length is {len(y)}")

print("Our X and y has been defined")

Intialization of model training....
Our y is        Open     High      Low      Avg    Close      Chg        Volume  \
3   72940.0  73719.0  72637.0  73088.0  73057.0  0.16000  2.049370e+10
4   71780.0  73358.0  71463.0  72391.0  72965.0  1.65000  2.423035e+10
5   71068.0  72871.0  70542.0  71568.0  71791.0  1.02000  2.449907e+10
6   71936.0  72721.0  70880.0  71663.0  71116.0 -1.14000  1.208696e+10
7   68831.0  72400.0  67798.0  70241.0  71935.0  4.51000  1.365453e+10
8   69293.0  70225.0  68532.0  69224.0  68848.0 -0.64200  1.068227e+10
9   67291.0  69022.0  66633.0  67983.0  68987.0  2.52000  6.060569e+09
10  66914.0  67472.0  66800.0  67121.0  67298.0  0.57300  4.092702e+09
11  66943.0  67235.0  66340.0  66863.0  66936.0 -0.00945  5.898220e+09
12  68086.0  68595.0  65790.0  67339.0  66883.0 -1.77000  1.039335e+10
13  68121.0  69189.0  67572.0  68250.0  68119.0 -0.00341  1.011372e+10
14  66703.0  68312.0  66025.0  67314.0  68217.0  2.27000  1.256418e+10
15  65896.0  67979.0  65826.0  66600.0  66698.0  1.22000  1.085729e+10
16  66341.0  66994.0  65237.0  66140.0  65987.0 -0.53500  6.226367e+09

    Vol Chg    Market Cap  MCap Chg
3    -15.42  1.462192e+12    0.1270
4     -1.10  1.460334e+12    1.6400
5    102.69  1.436806e+12    0.9510
6    -11.48  1.423263e+12   -1.1400
7     27.82  1.439626e+12    4.4900
8     76.26  1.377814e+12   -0.1990
9     48.08  1.380564e+12    2.5100
10   -30.61  1.346721e+12    0.5420
11   -43.25  1.339468e+12    0.0818
12     2.76  1.338373e+12   -1.8100
13   -19.50  1.363069e+12   -0.1410
14    15.72  1.364994e+12    2.2800
15    74.38  1.334587e+12    1.0800
16     7.89  1.320320e+12   -0.5150
its length is 14
Our X is        Open     High      Low      Avg    Close      Chg        Volume  \
17  66327.0  67181.0  65953.0  66448.0  66330.0  0.00529  5.771187e+09
18  68761.0  69073.0  65593.0  67437.0  66320.0 -3.55000  1.237285e+10
19  71307.0  71372.0  68240.0  69926.0  68786.0 -3.54000  1.072265e+10
20  70526.0  71912.0  70416.0  71044.0  71322.0  1.13000  9.579426e+09
21  70778.0  71285.0  68984.0  70400.0  70554.0 -0.31700  1.116488e+10
22  67847.0  71604.0  67600.0  69457.0  70775.0  4.32000  1.493409e+10
23  69263.0  69456.0  67570.0  68549.0  67906.0 -1.96000  8.672859e+09
24  70535.0  70949.0  69391.0  70067.0  69391.0 -1.62000  5.150024e+09
25  69922.0  71231.0  69560.0  70312.0  70534.0  0.87600  1.067312e+10
26  71267.0  71510.0  68996.0  70414.0  69886.0 -1.94000  1.236105e+10
27  73950.0  74565.0  70710.0  72632.0  71304.0 -3.58000  1.244954e+10
28  74829.0  75876.0  73632.0  74578.0  73977.0 -1.14000  1.414047e+10
29  72845.0  74850.0  72413.0  73733.0  74823.0  2.72000  1.591343e+10
30  71208.0  73008.0  70914.0  71953.0  72681.0  2.07000  8.024545e+09

    Vol Chg    Market Cap  MCap Chg
17  -53.360  1.327161e+12    0.0355
18   15.390  1.326690e+12   -3.5800
19   11.930  1.375931e+12   -3.5600
20  -14.200  1.426661e+12    1.0900
21  -25.240  1.411294e+12   -0.3120
22   72.190  1.415715e+12    4.2300
23   68.400  1.358322e+12   -2.1400
24  -51.750  1.388040e+12   -1.6200
25  -13.660  1.410901e+12    0.9280
26   -0.711  1.397928e+12   -1.9900
27  -11.960  1.426297e+12   -3.6100
28  -11.140  1.479756e+12   -1.1300
29   98.310  1.496679e+12    2.9500
30   30.860  1.453811e+12    2.1200
its length is 14
Our X and y has been defined

In [23]:
#7. Model training

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()

model.fit(X_train, y_train)
print("Model training complete!")

predictions = model.predict(X_test)

mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print(f"The Mean Squared Error is {mse} but lower value is better while the R2 is {r2} but closer to 1.00 is better")

Model training complete!
The Mean Squared Error is 2.4255262646872204e+26 but lower value is better while the R2 is -3503919.664155893 but closer to 1.00 is better

In [21]:
result = model.predict(our_sample)

print(f"The predicted BTC data is {result}")

The predicted BTC data is [[8.98620906e+06 1.14780946e+07 1.02022868e+07 1.00127084e+07
  9.38082843e+06 7.07703787e+02 2.20954108e+13 2.56053886e+05
  1.88270326e+14 6.30119681e+02]
 [8.62732033e+06 1.10204308e+07 9.79356827e+06 9.61297288e+06
  9.00729311e+06 6.80829264e+02 2.12161900e+13 2.45806339e+05
  1.80773292e+14 6.06780693e+02]
 [8.57383940e+06 1.09567241e+07 9.73755538e+06 9.55696329e+06
  8.95646293e+06 6.84226538e+02 2.10927725e+13 2.44796641e+05
  1.79753498e+14 6.10285681e+02]]